apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: helo
    spec:
      containers:
        - name: hello
          image: ghcr.io/stefanprodan/podinfo:6.6.2-latest
          ports:
            - containerPort: 9898
              name: http
          env:
            - name: PODINFO_UI_COLOR
              value: "#34577c"
            - name: PODINFO_UI_MESSAGE
              value: "If you can read this, you fixed all five bugs. Post it."
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
