apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-dev
resources:
  - ../../base
  - namespace.yaml
replicas:
  - name: hello
    count: 3
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: does-not-exist
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "Hello from DEV. Edited by Endah to prove GitOps works with argocd."
    target:
      kind: Deployment
      name: hello
